### ISSUE TITLE
Several logging of "Centrale non connessa" and sensors unavailable during reconnection

### ISSUE THREAD

**Issue by coserotondo** [palazzem/ha-econnect-alarm#121] opened 2024-01-22 14:46 UTC
**Describe the bug**
Several logging of "Centrale non connessa" and sensors unavailable during reconnection.

**Error message**
`2024-01-22 11:13:13.883 ERROR (SyncWorker_3) [custom_components.econnect_metronet.devices] Device | Error during the update: "Centrale non connessa"
2024-01-22 11:13:18.816 ERROR (MainThread) [custom_components.econnect_metronet.coordinator] Coordinator | Central unit disconnected, forcing a full update`

**Environment**
 - Operating System (OS): HAOS 11.4
 - Library version (commit or version number): 2.2.1
 - Home Assistant version: 2024.1.3
 - Last working Home Assistant release (if known): -

**Comment by palazzem** [comment] 2024-01-22 18:29
Thank for raising the issue! This error is expected if the central unit or the cloud API decide to reset the connection. I will investigate more to:
- Be 100% sure we can downgrade the message from ERROR to INFO (if it's expected, you should not be worried about).
- Avoid sensors to be unavailable for a very short amount of time. This improves the user experience.

Thanks again! I'll try to go at the bottom of it!

**Comment by palazzem** [comment] 2024-02-01 17:19
This is partially solved in https://github.com/palazzem/ha-econnect-alarm/pull/130 where these log messages are now considered `DEBUG`. I'd say we can close this issue as sensors are set to "Unavailable" if the integration can't communicate with the main unit, that makes sense if there is an actual connection issue.

Anyway, I'm planning to rewrite the collector logic to solve the actual root cause, meaning keep the connection as much stable as possibile. This is going to be solved in https://github.com/palazzem/ha-econnect-alarm/issues/76 .

**Closed by palazzem** 2024-02-01 17:19 UTC
Labels: topic:collector, type:bug
